lib = -fopenmp
st = --std=c++20

task3_1: task3_1.cpp
	g++ -o $@ task3_1.cpp $(lib) -std=c++20

task3.2_server: task3.2_server.cpp
	g++ -o $@ task3.2_server.cpp $(lib) -std=c++20

task3.2_check: task3.2_check.cpp
	g++ -o $@ task3.2_check.cpp $(lib) -std=c++20
